/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StartRouteImport } from './routes/start'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScanIndexRouteImport } from './routes/scan.index'
import { Route as HistoryIndexRouteImport } from './routes/history.index'
import { Route as ScanUploadRouteImport } from './routes/scan.upload'
import { Route as ScanGuideRouteImport } from './routes/scan.guide'
import { Route as OnboardingRestrictedRouteImport } from './routes/onboarding.restricted'
import { Route as OnboardingInfoRouteImport } from './routes/onboarding.info'
import { Route as OnboardingGoalRouteImport } from './routes/onboarding.goal'
import { Route as OnboardingFocusRouteImport } from './routes/onboarding.focus'
import { Route as OnboardingCompleteRouteImport } from './routes/onboarding.complete'
import { Route as HistoryIdRouteImport } from './routes/history.$id'
import { Route as AnalyzeSavedRouteImport } from './routes/analyze.saved'
import { Route as AnalyzeResultRouteImport } from './routes/analyze.result'
import { Route as AnalyzeLoadingRouteImport } from './routes/analyze.loading'

const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanIndexRoute = ScanIndexRouteImport.update({
  id: '/scan/',
  path: '/scan/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIndexRoute = HistoryIndexRouteImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanUploadRoute = ScanUploadRouteImport.update({
  id: '/scan/upload',
  path: '/scan/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanGuideRoute = ScanGuideRouteImport.update({
  id: '/scan/guide',
  path: '/scan/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRestrictedRoute = OnboardingRestrictedRouteImport.update({
  id: '/onboarding/restricted',
  path: '/onboarding/restricted',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingInfoRoute = OnboardingInfoRouteImport.update({
  id: '/onboarding/info',
  path: '/onboarding/info',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingGoalRoute = OnboardingGoalRouteImport.update({
  id: '/onboarding/goal',
  path: '/onboarding/goal',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingFocusRoute = OnboardingFocusRouteImport.update({
  id: '/onboarding/focus',
  path: '/onboarding/focus',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingCompleteRoute = OnboardingCompleteRouteImport.update({
  id: '/onboarding/complete',
  path: '/onboarding/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIdRoute = HistoryIdRouteImport.update({
  id: '/history/$id',
  path: '/history/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeSavedRoute = AnalyzeSavedRouteImport.update({
  id: '/analyze/saved',
  path: '/analyze/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeResultRoute = AnalyzeResultRouteImport.update({
  id: '/analyze/result',
  path: '/analyze/result',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeLoadingRoute = AnalyzeLoadingRouteImport.update({
  id: '/analyze/loading',
  path: '/analyze/loading',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/home': typeof HomeRoute
  '/start': typeof StartRoute
  '/analyze/loading': typeof AnalyzeLoadingRoute
  '/analyze/result': typeof AnalyzeResultRoute
  '/analyze/saved': typeof AnalyzeSavedRoute
  '/history/$id': typeof HistoryIdRoute
  '/onboarding/complete': typeof OnboardingCompleteRoute
  '/onboarding/focus': typeof OnboardingFocusRoute
  '/onboarding/goal': typeof OnboardingGoalRoute
  '/onboarding/info': typeof OnboardingInfoRoute
  '/onboarding/restricted': typeof OnboardingRestrictedRoute
  '/scan/guide': typeof ScanGuideRoute
  '/scan/upload': typeof ScanUploadRoute
  '/history/': typeof HistoryIndexRoute
  '/scan/': typeof ScanIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/home': typeof HomeRoute
  '/start': typeof StartRoute
  '/analyze/loading': typeof AnalyzeLoadingRoute
  '/analyze/result': typeof AnalyzeResultRoute
  '/analyze/saved': typeof AnalyzeSavedRoute
  '/history/$id': typeof HistoryIdRoute
  '/onboarding/complete': typeof OnboardingCompleteRoute
  '/onboarding/focus': typeof OnboardingFocusRoute
  '/onboarding/goal': typeof OnboardingGoalRoute
  '/onboarding/info': typeof OnboardingInfoRoute
  '/onboarding/restricted': typeof OnboardingRestrictedRoute
  '/scan/guide': typeof ScanGuideRoute
  '/scan/upload': typeof ScanUploadRoute
  '/history': typeof HistoryIndexRoute
  '/scan': typeof ScanIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/home': typeof HomeRoute
  '/start': typeof StartRoute
  '/analyze/loading': typeof AnalyzeLoadingRoute
  '/analyze/result': typeof AnalyzeResultRoute
  '/analyze/saved': typeof AnalyzeSavedRoute
  '/history/$id': typeof HistoryIdRoute
  '/onboarding/complete': typeof OnboardingCompleteRoute
  '/onboarding/focus': typeof OnboardingFocusRoute
  '/onboarding/goal': typeof OnboardingGoalRoute
  '/onboarding/info': typeof OnboardingInfoRoute
  '/onboarding/restricted': typeof OnboardingRestrictedRoute
  '/scan/guide': typeof ScanGuideRoute
  '/scan/upload': typeof ScanUploadRoute
  '/history/': typeof HistoryIndexRoute
  '/scan/': typeof ScanIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/home'
    | '/start'
    | '/analyze/loading'
    | '/analyze/result'
    | '/analyze/saved'
    | '/history/$id'
    | '/onboarding/complete'
    | '/onboarding/focus'
    | '/onboarding/goal'
    | '/onboarding/info'
    | '/onboarding/restricted'
    | '/scan/guide'
    | '/scan/upload'
    | '/history/'
    | '/scan/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/home'
    | '/start'
    | '/analyze/loading'
    | '/analyze/result'
    | '/analyze/saved'
    | '/history/$id'
    | '/onboarding/complete'
    | '/onboarding/focus'
    | '/onboarding/goal'
    | '/onboarding/info'
    | '/onboarding/restricted'
    | '/scan/guide'
    | '/scan/upload'
    | '/history'
    | '/scan'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/home'
    | '/start'
    | '/analyze/loading'
    | '/analyze/result'
    | '/analyze/saved'
    | '/history/$id'
    | '/onboarding/complete'
    | '/onboarding/focus'
    | '/onboarding/goal'
    | '/onboarding/info'
    | '/onboarding/restricted'
    | '/scan/guide'
    | '/scan/upload'
    | '/history/'
    | '/scan/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  HomeRoute: typeof HomeRoute
  StartRoute: typeof StartRoute
  AnalyzeLoadingRoute: typeof AnalyzeLoadingRoute
  AnalyzeResultRoute: typeof AnalyzeResultRoute
  AnalyzeSavedRoute: typeof AnalyzeSavedRoute
  HistoryIdRoute: typeof HistoryIdRoute
  OnboardingCompleteRoute: typeof OnboardingCompleteRoute
  OnboardingFocusRoute: typeof OnboardingFocusRoute
  OnboardingGoalRoute: typeof OnboardingGoalRoute
  OnboardingInfoRoute: typeof OnboardingInfoRoute
  OnboardingRestrictedRoute: typeof OnboardingRestrictedRoute
  ScanGuideRoute: typeof ScanGuideRoute
  ScanUploadRoute: typeof ScanUploadRoute
  HistoryIndexRoute: typeof HistoryIndexRoute
  ScanIndexRoute: typeof ScanIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/': {
      id: '/scan/'
      path: '/scan'
      fullPath: '/scan/'
      preLoaderRoute: typeof ScanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/': {
      id: '/history/'
      path: '/history'
      fullPath: '/history/'
      preLoaderRoute: typeof HistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/upload': {
      id: '/scan/upload'
      path: '/scan/upload'
      fullPath: '/scan/upload'
      preLoaderRoute: typeof ScanUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/guide': {
      id: '/scan/guide'
      path: '/scan/guide'
      fullPath: '/scan/guide'
      preLoaderRoute: typeof ScanGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/restricted': {
      id: '/onboarding/restricted'
      path: '/onboarding/restricted'
      fullPath: '/onboarding/restricted'
      preLoaderRoute: typeof OnboardingRestrictedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/info': {
      id: '/onboarding/info'
      path: '/onboarding/info'
      fullPath: '/onboarding/info'
      preLoaderRoute: typeof OnboardingInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/goal': {
      id: '/onboarding/goal'
      path: '/onboarding/goal'
      fullPath: '/onboarding/goal'
      preLoaderRoute: typeof OnboardingGoalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/focus': {
      id: '/onboarding/focus'
      path: '/onboarding/focus'
      fullPath: '/onboarding/focus'
      preLoaderRoute: typeof OnboardingFocusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/complete': {
      id: '/onboarding/complete'
      path: '/onboarding/complete'
      fullPath: '/onboarding/complete'
      preLoaderRoute: typeof OnboardingCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/$id': {
      id: '/history/$id'
      path: '/history/$id'
      fullPath: '/history/$id'
      preLoaderRoute: typeof HistoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze/saved': {
      id: '/analyze/saved'
      path: '/analyze/saved'
      fullPath: '/analyze/saved'
      preLoaderRoute: typeof AnalyzeSavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze/result': {
      id: '/analyze/result'
      path: '/analyze/result'
      fullPath: '/analyze/result'
      preLoaderRoute: typeof AnalyzeResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze/loading': {
      id: '/analyze/loading'
      path: '/analyze/loading'
      fullPath: '/analyze/loading'
      preLoaderRoute: typeof AnalyzeLoadingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  HomeRoute: HomeRoute,
  StartRoute: StartRoute,
  AnalyzeLoadingRoute: AnalyzeLoadingRoute,
  AnalyzeResultRoute: AnalyzeResultRoute,
  AnalyzeSavedRoute: AnalyzeSavedRoute,
  HistoryIdRoute: HistoryIdRoute,
  OnboardingCompleteRoute: OnboardingCompleteRoute,
  OnboardingFocusRoute: OnboardingFocusRoute,
  OnboardingGoalRoute: OnboardingGoalRoute,
  OnboardingInfoRoute: OnboardingInfoRoute,
  OnboardingRestrictedRoute: OnboardingRestrictedRoute,
  ScanGuideRoute: ScanGuideRoute,
  ScanUploadRoute: ScanUploadRoute,
  HistoryIndexRoute: HistoryIndexRoute,
  ScanIndexRoute: ScanIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
